import React, { useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import {
  AlertTriangle, BarChart3, Bold, Check, CheckCircle2, ChevronDown, Code2,
  Copy, Edit, Eye, EyeOff, ExternalLink, FileText, Image as ImageIcon, Italic, Link2, Loader2,
  Menu, Minus, Palette, Plus, Redo2, RefreshCw, Save, Search, Settings,
  Shield, Strikethrough, Trash2, Underline, Undo2, Upload, Users, X
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { TOOLS } from "@/lib/tools";
import { useSiteSettings, type SiteSettings } from "@/lib/site-settings";
import AdminCmsSettingsPanel from "@/components/admin-cms-settings-panel";

type Tab =
  | "dashboard" | "posts" | "pages" | "faqs" | "leads" | "reviews" | "comments" | "media"
  | "tools" | "appearance" | "social" | "adsense" | "analytics" | "seo" | "redirects"
  | "users" | "security" | "settings" | "cms";

type NavItem = { id: Tab; label: string; section: string };
const NAV: NavItem[] = [
  { id: "dashboard", label: "Dashboard", section: "Overview" },
  { id: "posts", label: "Posts / Articles", section: "Content" },
  { id: "pages", label: "Pages", section: "Content" },
  { id: "faqs", label: "FAQs", section: "Content" },
  { id: "comments", label: "Comments", section: "Content" },
  { id: "reviews", label: "Reviews", section: "Content" },
  { id: "leads", label: "Leads / Enquiries", section: "Content" },
  { id: "media", label: "Media Library", section: "Content" },
  { id: "tools", label: "Calculators / Tools", section: "Tools" },
  { id: "appearance", label: "Theme & Layout", section: "Website" },
  { id: "social", label: "Social Media", section: "Website" },
  { id: "adsense", label: "AdSense / Ads", section: "Monetization" },
  { id: "analytics", label: "Analytics", section: "SEO & Analytics" },
  { id: "seo", label: "SEO Settings", section: "SEO & Analytics" },
  { id: "redirects", label: "Redirects / 404", section: "SEO & Analytics" },
  { id: "users", label: "Users & Roles", section: "Security" },
  { id: "security", label: "Audit / Security", section: "Security" },
  { id: "cms", label: "CMS Settings", section: "System" },
  { id: "settings", label: "General Settings", section: "System" },
];

const inputCls = "w-full rounded-lg border border-input bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring/30";
const labelCls = "text-[11px] font-bold uppercase tracking-wide text-muted-foreground";
const slugify = (s: string) => s.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 100);

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-xl border border-border bg-card p-5 shadow-sm ${className}`}>{children}</section>;
}
function Button({ children, onClick, disabled = false, variant = "primary", type = "button" }: { children: React.ReactNode; onClick?: () => void; disabled?: boolean; variant?: "primary" | "ghost" | "danger"; type?: "button" | "submit" }) {
  const c = variant === "danger" ? "border-destructive text-destructive hover:bg-destructive/10" : variant === "ghost" ? "border-border hover:bg-secondary" : "bg-accent text-accent-foreground hover:opacity-90";
  return <button type={type} disabled={disabled} onClick={onClick} className={`inline-flex items-center justify-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-50 ${c}`}>{children}</button>;
}
function Field({ name, value, onChange, type = "text", placeholder = "", disabled = false }: { name: string; value: string; onChange: (v: string) => void; type?: string; placeholder?: string; disabled?: boolean }) {
  return <label className="grid gap-1"><span className={labelCls}>{name}</span><input disabled={disabled} className={inputCls} type={type} value={value} placeholder={placeholder} onChange={e => onChange(e.target.value)} /></label>;
}

function stripHtml(html: string) {
  if (!html) return "";
  const el = document.createElement("div"); el.innerHTML = html;
  return (el.textContent || el.innerText || "").replace(/\u00a0/g, " ").replace(/\s+/g, " ").trim();
}
function escapeHtml(v: string) { return v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#039;"); }
function normalizeText(v: string) { return v.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim(); }
function words(v: string) { return normalizeText(v).split(" ").filter(Boolean); }
function ngrams(v: string, n = 5) { const w = words(v); const out = new Set<string>(); for (let i = 0; i <= w.length - n; i++) out.add(w.slice(i, i + n).join(" ")); return out; }

function grammarCheck(text: string) {
  const issues: { type: "error" | "warning"; message: string }[] = [];
  if (!text.trim()) return issues;
  if (/ {2,}/.test(text)) issues.push({ type: "warning", message: "Multiple spaces found." });
  if (/\s+[,.!?;:]/.test(text)) issues.push({ type: "error", message: "Space before punctuation." });
  if (/[,.!?;:]{2,}/.test(text)) issues.push({ type: "warning", message: "Repeated punctuation." });
  if (/(^|[.!?]\s+)[a-z]/.test(text)) issues.push({ type: "error", message: "Sentence starts with lowercase letter." });
  if (/\bi\b/.test(text)) issues.push({ type: "error", message: "Pronoun “I” should be capitalized." });
  if (/\b(a|an)\s+[aeiou][a-z]+\b/i.test(text) && /\ba\s+[aeiou]/i.test(text)) issues.push({ type: "warning", message: "Check article: use “an” before a vowel sound." });
  if (/\b(he|she|it)\s+(are|were|have|do|go|make|need|use)\b/i.test(text)) issues.push({ type: "error", message: "Possible subject–verb agreement issue." });
  if (/\b(the|a|an)\s+[,.]/i.test(text)) issues.push({ type: "error", message: "Article followed by punctuation." });
  if (/\.{4,}/.test(text)) issues.push({ type: "warning", message: "Too many consecutive periods." });
  return issues;
}

function useSitePlagiarism(text: string, excludeId?: string | null) {
  const [state, setState] = useState<{ status: "idle" | "checking" | "green" | "red"; score: number | null; matches: string[] }>({ status: "idle", score: null, matches: [] });
  const check = async () => {
    const clean = normalizeText(text);
    if (clean.length < 80) { setState({ status: "idle", score: null, matches: [] }); return; }
    setState(s => ({ ...s, status: "checking" }));
    const current = ngrams(clean, 7);
    try {
      const [posts, pages, faqs] = await Promise.all([
        supabase.from("posts").select("id,title,content,body,excerpt"),
        supabase.from("pages").select("id,title,content,body,excerpt"),
        supabase.from("faqs").select("id,question,answer"),
      ]);
      const candidates: { id: string; title: string; text: string }[] = [];
      (posts.data || []).forEach((r: any) => candidates.push({ id: String(r.id), title: `Post: ${r.title || r.id}`, text: `${r.title || ""} ${r.excerpt || ""} ${r.content || r.body || ""}` }));
      (pages.data || []).forEach((r: any) => candidates.push({ id: String(r.id), title: `Page: ${r.title || r.id}`, text: `${r.title || ""} ${r.excerpt || ""} ${r.content || r.body || ""}` }));
      (faqs.data || []).forEach((r: any) => candidates.push({ id: String(r.id), title: `FAQ: ${r.question || r.id}`, text: `${r.question || ""} ${r.answer || ""}` }));
      let best = 0; const matches: string[] = [];
      for (const c of candidates) {
        if (excludeId && c.id === String(excludeId)) continue;
        const other = ngrams(c.text, 7); if (!other.size || !current.size) continue;
        let hit = 0; current.forEach(x => { if (other.has(x)) hit++; });
        const pct = hit / current.size * 100;
        if (pct > best) best = pct;
        if (pct >= 8) matches.push(`${c.title} (${Math.round(pct)}% phrase overlap)`);
      }
      const overlap = Math.min(100, Math.round(best));
      setState({ status: overlap >= 15 ? "red" : "green", score: overlap, matches: matches.slice(0, 5) });
    } catch { setState({ status: "idle", score: null, matches: [] }); }
  };
  useEffect(() => { const timer = window.setTimeout(() => { void check(); }, 900); return () => window.clearTimeout(timer); }, [text, excludeId]);
  return { state, check };
}

function EditorButton({ title, children, onClick }: { title: string; children: React.ReactNode; onClick: () => void }) {
  return <button type="button" title={title} aria-label={title} onMouseDown={e => e.preventDefault()} onClick={onClick} className="grid size-8 place-items-center rounded border border-border bg-background text-xs font-semibold hover:bg-secondary">{children}</button>;
}

function RichEditor({ value, onChange, placeholder = "Start writing...", minHeight = 420, showQuality = true, allowMedia = true, plagiarismId = null }: { value: string; onChange: (v: string) => void; placeholder?: string; minHeight?: number; showQuality?: boolean; allowMedia?: boolean; plagiarismId?: string | null }) {
  const ref = useRef<HTMLDivElement>(null); const [source, setSource] = useState(false); const [font, setFont] = useState("Arial"); const [size, setSize] = useState("3");
  const [qualityOpen, setQualityOpen] = useState(false); const [grammar, setGrammar] = useState<{ type: "error" | "warning"; message: string }[]>([]); const [mediaOpen, setMediaOpen] = useState(false); const plagiarism = useSitePlagiarism(stripHtml(value), plagiarismId);
  const sync = () => { const html = ref.current?.innerHTML || ""; onChange(html); setGrammar(grammarCheck(stripHtml(html))); };
  useEffect(() => { if (!ref.current || source) return; const html = /<[a-z][\s\S]*>/i.test(value) ? value : value ? value.split(/\r?\n/).map(x => `<p>${escapeHtml(x) || "<br>"}</p>`).join("") : ""; if (ref.current.innerHTML !== html) ref.current.innerHTML = html; setGrammar(grammarCheck(stripHtml(value))); }, [value, source]);
  const command = (cmd: string, arg?: string) => { ref.current?.focus(); document.execCommand(cmd, false, arg); sync(); };
  const link = () => { const url = window.prompt("Enter URL"); if (url) command("createLink", url); };
  const insertImage = () => { const url = window.prompt("Image URL"); if (url) command("insertImage", url); };
  const insertHtml = () => { const html = window.prompt("HTML to insert"); if (html) command("insertHTML", html); };
  return <div className="overflow-hidden rounded-xl border border-input bg-background">
    {mediaOpen && <MediaPicker onSelect={url => { command("insertImage", url); setMediaOpen(false); }} onClose={() => setMediaOpen(false)} />}
    <div className="flex flex-wrap items-center gap-1 border-b border-border bg-secondary/40 p-2">
      <EditorButton title="Undo" onClick={() => command("undo")}><Undo2 className="size-4" /></EditorButton><EditorButton title="Redo" onClick={() => command("redo")}><Redo2 className="size-4" /></EditorButton><span className="mx-1 h-5 w-px bg-border" />
      <select aria-label="Block style" className="h-8 rounded border border-border bg-background px-2 text-xs" defaultValue="p" onChange={e => command("formatBlock", `<${e.target.value}>`)}><option value="p">Paragraph</option><option value="h1">H1</option><option value="h2">H2</option><option value="h3">H3</option><option value="h4">H4</option><option value="blockquote">Quote</option><option value="pre">Code</option></select>
      <select aria-label="Font family" className="h-8 rounded border border-border bg-background px-2 text-xs" value={font} onChange={e => { setFont(e.target.value); command("fontName", e.target.value); }}><option>Arial</option><option>Georgia</option><option>Times New Roman</option><option>Verdana</option><option>Trebuchet MS</option><option>Courier New</option></select>
      <select aria-label="Font size" className="h-8 rounded border border-border bg-background px-2 text-xs" value={size} onChange={e => { setSize(e.target.value); command("fontSize", e.target.value); }}><option value="1">8</option><option value="2">10</option><option value="3">14</option><option value="4">18</option><option value="5">24</option><option value="6">32</option><option value="7">48</option></select>
      <span className="mx-1 h-5 w-px bg-border" />
      <EditorButton title="Bold" onClick={() => command("bold")}><Bold className="size-4" /></EditorButton><EditorButton title="Italic" onClick={() => command("italic")}><Italic className="size-4" /></EditorButton><EditorButton title="Underline" onClick={() => command("underline")}><Underline className="size-4" /></EditorButton><EditorButton title="Strike" onClick={() => command("strikeThrough")}><Strikethrough className="size-4" /></EditorButton>
      <EditorButton title="Bulleted list" onClick={() => command("insertUnorderedList")}>•</EditorButton><EditorButton title="Numbered list" onClick={() => command("insertOrderedList")}>1.</EditorButton>
      <EditorButton title="Align left" onClick={() => command("justifyLeft")}>L</EditorButton><EditorButton title="Align center" onClick={() => command("justifyCenter")}>C</EditorButton><EditorButton title="Align right" onClick={() => command("justifyRight")}>R</EditorButton><EditorButton title="Justify" onClick={() => command("justifyFull")}>J</EditorButton>
      <EditorButton title="Insert link" onClick={link}><Link2 className="size-4" /></EditorButton><EditorButton title="Remove link" onClick={() => command("unlink")}>×</EditorButton><EditorButton title="Horizontal rule" onClick={() => command("insertHorizontalRule")}><Minus className="size-4" /></EditorButton>
      {allowMedia && <><EditorButton title="Insert image from Media Library" onClick={() => setMediaOpen(true)}><Upload className="size-4" /></EditorButton><EditorButton title="Insert image by URL" onClick={insertImage}><ImageIcon className="size-4" /></EditorButton><EditorButton title="Insert HTML" onClick={insertHtml}><Code2 className="size-4" /></EditorButton></>}
      <EditorButton title="Clear formatting" onClick={() => command("removeFormat")}>Tx</EditorButton>
      <button type="button" className="ml-auto rounded border border-border px-2 py-1 text-xs font-semibold" onClick={() => setSource(v => !v)}>{source ? "Visual" : "HTML"}</button>
    </div>
    {source ? <textarea value={value} onChange={e => { onChange(e.target.value); setGrammar(grammarCheck(stripHtml(e.target.value))); }} spellCheck className="w-full resize-y border-0 bg-background p-4 font-mono text-sm outline-none" style={{ minHeight }} /> : <div ref={ref} contentEditable suppressContentEditableWarning spellCheck role="textbox" aria-multiline="true" data-placeholder={placeholder} onInput={sync} className="prose prose-sm max-w-none overflow-y-auto bg-background p-4 leading-7 outline-none empty:before:text-muted-foreground/50 empty:before:content-[attr(data-placeholder)]" style={{ minHeight }} />}
    {showQuality && <div className="border-t border-border bg-secondary/20 p-3 text-xs">
      <div className="flex flex-wrap items-center gap-3"><span>{stripHtml(value).split(/\s+/).filter(Boolean).length} words</span><span>{stripHtml(value).length} chars</span><button type="button" onClick={() => setQualityOpen(v => !v)} className="font-semibold underline">Writing quality</button><span className="ml-auto inline-flex items-center gap-1 font-semibold">{grammar.length ? <><AlertTriangle className="size-3.5 text-red-600" /> {grammar.length} grammar issue(s)</> : <><CheckCircle2 className="size-3.5 text-emerald-600" /> Grammar checks clear</>}</span><span className="font-semibold">Plagiarism:</span>{plagiarism.state.status === "checking" ? <span>Checking…</span> : plagiarism.state.status === "green" ? <span className="font-semibold text-emerald-600">GREEN · {plagiarism.state.score}% overlap</span> : plagiarism.state.status === "red" ? <span className="font-semibold text-red-600">RED · {plagiarism.state.score}% overlap</span> : <span className="text-muted-foreground">Not checked</span>}<button type="button" onClick={() => void plagiarism.check()} className="rounded border border-border px-2 py-1 font-semibold">Check</button></div>
      {qualityOpen && <div className="mt-3 grid gap-2">{grammar.length ? grammar.map((x, i) => <div key={i} className={x.type === "error" ? "text-red-600" : "text-amber-600"}>• {x.message}</div>) : <div className="text-emerald-600">No local grammar-rule issues detected. Browser spellcheck is also enabled.</div>}{plagiarism.state.matches.length > 0 && <div className="mt-2"><div className="font-semibold">Matching site content</div>{plagiarism.state.matches.map((m, i) => <div key={i} className="text-red-600">• {m}</div>)}</div>}</div>}
      <div className="mt-2 text-[10px] text-muted-foreground">Plagiarism is checked against this site's stored Posts, Pages and FAQs; it is not an internet-wide plagiarism service.</div>
    </div>}
  </div>;
}

function MediaPicker({ onSelect, onClose }: { onSelect: (url: string) => void; onClose: () => void }) {
  const [items, setItems] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const load = async () => { const r = await supabase.from("media_items").select("*").order("created_at", { ascending: false }); if (!r.error) setItems(r.data || []); };
  useEffect(() => { void load(); }, []);
  const upload = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); const path = `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const up = await supabase.storage.from("admin-media").upload(path, file, { upsert: false }); if (up.error) { setBusy(false); toast.error(up.error.message); return; } const url = supabase.storage.from("admin-media").getPublicUrl(path).data.publicUrl; const ins = await supabase.from("media_items").insert({ name: file.name, url, path, mime_type: file.type, size_bytes: file.size }); setBusy(false); if (ins.error) toast.error(ins.error.message); else { toast.success("Image uploaded"); void load(); } };
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="max-h-[85vh] w-full max-w-4xl overflow-auto rounded-xl bg-card p-5 shadow-xl"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Media Library</h3><p className="text-xs text-muted-foreground">Select an existing image or upload a new one.</p></div><Button variant="ghost" onClick={onClose}><X className="size-4" /></Button></div><div className="mt-4"><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-accent-foreground"><input className="hidden" type="file" accept="image/*" onChange={upload} />{busy ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />} Upload image</label></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">{items.map(i => <button type="button" key={i.id} onClick={() => { onSelect(i.url); onClose(); }} className="overflow-hidden rounded-lg border border-border text-left hover:ring-2 hover:ring-accent"><img src={i.url} alt={i.alt_text || i.name} className="aspect-square w-full object-cover" /><div className="truncate p-2 text-[11px]">{i.name}</div></button>)}</div></div></div>;
}

function PostsPanel() {
  const qc = useQueryClient(); const [id, setId] = useState<string | null>(null); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [excerpt, setExcerpt] = useState(""); const [body, setBody] = useState(""); const [published, setPublished] = useState(true); const [image, setImage] = useState(""); const [category, setCategory] = useState("General"); const [tags, setTags] = useState(""); const [metaTitle, setMetaTitle] = useState(""); const [metaDescription, setMetaDescription] = useState(""); const [saving, setSaving] = useState(false); const [picker, setPicker] = useState(false);
  const q = useQuery({ queryKey: ["admin_posts_master"], queryFn: async () => { let r = await supabase.from("posts").select("*").order("created_at", { ascending: false }); if (r.error || !r.data?.length) r = await supabase.from("blog_posts").select("*").order("created_at", { ascending: false }); return r.data || []; } });
  const reset = () => { setId(null); setTitle(""); setSlug(""); setExcerpt(""); setBody(""); setPublished(true); setImage(""); setCategory("General"); setTags(""); setMetaTitle(""); setMetaDescription(""); };
  const edit = (p: any) => { setId(p.id); setTitle(p.title || ""); setSlug(p.slug || ""); setExcerpt(p.excerpt || ""); setBody(p.content || p.body || ""); setPublished(p.published !== false); setImage(p.featured_image || ""); setCategory(p.category || "General"); setTags(p.tags || ""); setMetaTitle(p.meta_title || p.seo_title || ""); setMetaDescription(p.meta_description || p.seo_description || ""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function save() { if (title.trim().length < 3) return toast.error("Article title required"); setSaving(true); const payload: any = { title: title.trim(), slug: slugify(slug || title), excerpt: excerpt.trim() || null, content: body, published, featured_image: image.trim() || null, category: category.trim() || "General", tags: tags.trim() || null, meta_title: metaTitle.trim() || null, meta_description: metaDescription.trim() || null, updated_at: new Date().toISOString() }; let r = id ? await supabase.from("posts").update(payload).eq("id", id) : await supabase.from("posts").insert(payload); if (r.error) { const fallback: any = { title: payload.title, slug: payload.slug, excerpt: payload.excerpt, content: payload.content, published: payload.published, featured_image: payload.featured_image }; r = id ? await supabase.from("posts").update(fallback).eq("id", id) : await supabase.from("posts").insert(fallback); } setSaving(false); if (r.error) return toast.error(r.error.message); toast.success(id ? "Article updated" : "Article saved"); reset(); void qc.invalidateQueries({ queryKey: ["admin_posts_master"] }); }
  async function del(postId: string) { if (!confirm("Delete this article?")) return; const r = await supabase.from("posts").delete().eq("id", postId); if (r.error) toast.error(r.error.message); else { toast.success("Article deleted"); void qc.invalidateQueries({ queryKey: ["admin_posts_master"] }); } }
  return <div className="space-y-6">{picker && <MediaPicker onSelect={setImage} onClose={() => setPicker(false)} />}<Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{id ? "Edit Article" : "Create Article"}</h2><p className="text-xs text-muted-foreground">Article editor only: rich text, SEO, featured image and publishing.</p></div>{id && <Button variant="ghost" onClick={reset}><X className="size-4" />Cancel edit</Button>}</div><div className="mt-5 grid gap-4"><Field name="Title" value={title} onChange={v => { setTitle(v); if (!id) setSlug(slugify(v)); }} /><Field name="Permalink / Slug" value={slug} onChange={setSlug} /><Field name="Excerpt" value={excerpt} onChange={setExcerpt} /><div><span className={labelCls}>Article content</span><div className="mt-1"><RichEditor value={body} onChange={setBody} placeholder="Write the article..." minHeight={540} plagiarismId={id} /></div></div><div className="grid gap-4 sm:grid-cols-2"><Field name="Category" value={category} onChange={setCategory} /><Field name="Tags" value={tags} onChange={setTags} /></div><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><Field name="Featured image URL" value={image} onChange={setImage} placeholder="https://..." /><div className="flex items-end"><Button variant="ghost" onClick={() => setPicker(true)}><ImageIcon className="size-4" />Choose image</Button></div></div>{image && <img src={image} alt="Featured" className="max-h-64 rounded-lg border border-border object-cover" />}<div className="grid gap-4 sm:grid-cols-2"><Field name="SEO title" value={metaTitle} onChange={setMetaTitle} /><Field name="SEO description" value={metaDescription} onChange={setMetaDescription} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={published} onChange={e => setPublished(e.target.checked)} />Published / visible</label><Button disabled={saving} onClick={() => void save()}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}{id ? "Update Article" : "Save Article"}</Button></div></Card><Card><h3 className="mb-4 font-bold">Existing Articles ({q.data?.length || 0})</h3><div className="grid gap-2">{(q.data || []).map((p: any) => <div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"><div><div className="font-medium">{p.title}</div><div className="text-xs text-muted-foreground">/{p.slug} · {p.published === false ? "Draft" : "Published"}</div></div><div className="flex gap-2"><Button variant="ghost" onClick={() => edit(p)}><FileText className="size-4" />Edit</Button><Button variant="danger" onClick={() => void del(p.id)}><Trash2 className="size-4" />Delete</Button></div></div>)}</div></Card></div>;
}

function PagesPanel() {
  const qc = useQueryClient(); const [id, setId] = useState<string | null>(null); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [content, setContent] = useState(""); const q = useQuery({ queryKey: ["admin_pages_master"], queryFn: async () => { const r = await supabase.from("pages").select("*").order("created_at", { ascending: false }); return r.data || []; } });
  const reset = () => { setId(null); setTitle(""); setSlug(""); setContent(""); }; const edit = (p: any) => { setId(p.id); setTitle(p.title || ""); setSlug(p.slug || ""); setContent(p.content || p.body || ""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function save() { if (title.trim().length < 3) return toast.error("Page title required"); const payload = { title: title.trim(), slug: slugify(slug || title), content }; const r = id ? await supabase.from("pages").update(payload).eq("id", id) : await supabase.from("pages").insert(payload); if (r.error) return toast.error(r.error.message); toast.success(id ? "Page updated" : "Page created"); reset(); void qc.invalidateQueries({ queryKey: ["admin_pages_master"] }); }
  async function del(pageId: string) { if (!confirm("Delete page?")) return; const r = await supabase.from("pages").delete().eq("id", pageId); if (r.error) toast.error(r.error.message); else { toast.success("Page deleted"); void qc.invalidateQueries({ queryKey: ["admin_pages_master"] }); } }
  return <div className="space-y-5"><Card><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">{id ? "Edit Page" : "Create Page"}</h2><p className="text-xs text-muted-foreground">Page-specific editor; no article metadata forced here.</p></div>{id && <Button variant="ghost" onClick={reset}><X className="size-4" />Cancel</Button>}</div><div className="mt-5 grid gap-4"><Field name="Page title" value={title} onChange={v => { setTitle(v); if (!id) setSlug(slugify(v)); }} /><Field name="Slug" value={slug} onChange={setSlug} /><div><span className={labelCls}>Page content</span><div className="mt-1"><RichEditor value={content} onChange={setContent} minHeight={500} /></div></div><Button onClick={() => void save()}><Save className="size-4" />{id ? "Update Page" : "Create Page"}</Button></div></Card><Card><h3 className="mb-4 font-bold">Existing Pages</h3><div className="grid gap-2">{(q.data || []).map((p: any) => <div key={p.id} className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"><div><b>{p.title}</b><div className="text-xs text-muted-foreground">/{p.slug}</div></div><div className="flex gap-2"><Button variant="ghost" onClick={() => edit(p)}>Edit</Button><Button variant="danger" onClick={() => void del(p.id)}><Trash2 className="size-4" /></Button></div></div>)}</div></Card></div>;
}

function FaqsPanel() {
  const qc = useQueryClient(); const [id, setId] = useState<string | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const q = useQuery({ queryKey: ["admin_faqs_master"], queryFn: async () => { const r = await supabase.from("faqs").select("*").order("created_at", { ascending: false }); return r.data || []; } });
  const reset = () => { setId(null); setQuestion(""); setAnswer(""); }; const edit = (f: any) => { setId(f.id); setQuestion(f.question || ""); setAnswer(f.answer || ""); window.scrollTo({ top: 0, behavior: "smooth" }); };
  async function save() { if (question.trim().length < 4 || answer.trim().length < 4) return toast.error("Question and answer are required"); const payload = { question: question.trim(), answer }; const r = id ? await supabase.from("faqs").update(payload).eq("id", id) : await supabase.from("faqs").insert(payload); if (r.error) return toast.error(r.error.message); toast.success(id ? "FAQ updated" : "FAQ added"); reset(); void qc.invalidateQueries({ queryKey: ["admin_faqs_master"] }); }
  async function del(faqId: string) { if (!confirm("Delete FAQ?")) return; const r = await supabase.from("faqs").delete().eq("id", faqId); if (r.error) toast.error(r.error.message); else { toast.success("FAQ deleted"); void qc.invalidateQueries({ queryKey: ["admin_faqs_master"] }); } }
  return <div className="space-y-5"><Card><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">{id ? "Edit FAQ" : "Add FAQ"}</h2><p className="text-xs text-muted-foreground">FAQ answer editor only.</p></div>{id && <Button variant="ghost" onClick={reset}><X className="size-4" />Cancel</Button>}</div><div className="mt-5 grid gap-4"><Field name="Question" value={question} onChange={setQuestion} /><div><span className={labelCls}>Answer</span><div className="mt-1"><RichEditor value={answer} onChange={setAnswer} minHeight={300} /></div></div><Button onClick={() => void save()}><Save className="size-4" />{id ? "Update FAQ" : "Add FAQ"}</Button></div></Card><Card><h3 className="mb-4 font-bold">Existing FAQs</h3><div className="grid gap-2">{(q.data || []).map((f: any) => <div key={f.id} className="flex items-center justify-between gap-3 rounded-lg border border-border p-3"><div className="min-w-0"><b>{f.question}</b><div className="truncate text-xs text-muted-foreground">{stripHtml(f.answer || "")}</div></div><div className="flex gap-2"><Button variant="ghost" onClick={() => edit(f)}>Edit</Button><Button variant="danger" onClick={() => void del(f.id)}><Trash2 className="size-4" /></Button></div></div>)}</div></Card></div>;
}

function ToolsPanel() {
  const qc = useQueryClient(); const [selected, setSelected] = useState(TOOLS[0]?.slug || ""); const tool = useMemo(() => TOOLS.find(t => t.slug === selected), [selected]); const [name, setName] = useState(""); const [category, setCategory] = useState(""); const [description, setDescription] = useState(""); const [longDescription, setLongDescription] = useState(""); const [status, setStatus] = useState("Active"); const [featured, setFeatured] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { if (!selected) return; const r = await supabase.from("site_settings").select("value").eq("key", `tool_cfg_${selected}`).maybeSingle(); const v: any = r.data?.value || {}; setName(v.customName || tool?.name || ""); setCategory(v.category || tool?.category || "General"); setDescription(v.description || tool?.description || ""); setLongDescription(v.longDescription || ""); setStatus(v.status || "Active"); setFeatured(!!v.featured); })(); }, [selected, tool]);
  async function save() { if (!selected) return; setSaving(true); const r = await supabase.from("site_settings").upsert({ key: `tool_cfg_${selected}`, value: { customName: name, category, description, longDescription, status, featured }, updated_at: new Date().toISOString() }, { onConflict: "key" }); setSaving(false); if (r.error) toast.error(r.error.message); else { toast.success("Calculator settings saved"); void qc.invalidateQueries(); } }
  return <div className="space-y-5"><Card><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Calculator / Tool Manager</h2><p className="text-xs text-muted-foreground">Tool-specific settings only. The calculator logic itself remains in the existing tool component.</p></div><span className="rounded-full border border-border px-3 py-1 text-xs font-semibold">{TOOLS.length} tools</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-1 sm:col-span-2"><span className={labelCls}>Select calculator</span><select className={inputCls} value={selected} onChange={e => setSelected(e.target.value)}>{TOOLS.map(t => <option key={t.slug} value={t.slug}>{t.name} — {t.category}</option>)}</select></label><Field name="Display name" value={name} onChange={setName} /><Field name="Category" value={category} onChange={setCategory} /><label className="grid gap-1"><span className={labelCls}>Status</span><select className={inputCls} value={status} onChange={e => setStatus(e.target.value)}><option>Active</option><option>Maintenance</option><option>Disabled</option></select></label><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" checked={featured} onChange={e => setFeatured(e.target.checked)} /> Featured calculator</label><div><span className={labelCls}>Short description</span><textarea className={`${inputCls} mt-1 min-h-28`} value={description} onChange={e => setDescription(e.target.value)} /></div><div><span className={labelCls}>Long description</span><textarea className={`${inputCls} mt-1 min-h-28`} value={longDescription} onChange={e => setLongDescription(e.target.value)} /></div></div><div className="mt-4"><Button disabled={saving} onClick={() => void save()}><Save className="size-4" />Save calculator settings</Button></div></Card></div>;
}

function MediaPanel() {
  const [items, setItems] = useState<any[]>([]); const [busy, setBusy] = useState(false); const load = async () => { const r = await supabase.from("media_items").select("*").order("created_at", { ascending: false }); if (!r.error) setItems(r.data || []); }; useEffect(() => { void load(); }, []);
  async function upload(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; setBusy(true); const path = `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const up = await supabase.storage.from("admin-media").upload(path, file, { upsert: false }); if (up.error) { setBusy(false); return toast.error(up.error.message); } const url = supabase.storage.from("admin-media").getPublicUrl(path).data.publicUrl; const ins = await supabase.from("media_items").insert({ name: file.name, url, path, mime_type: file.type, size_bytes: file.size }); setBusy(false); if (ins.error) toast.error(ins.error.message); else { toast.success("Media uploaded"); void load(); } }
  async function del(i: any) { if (!confirm("Delete this media?")) return; if (i.path) await supabase.storage.from("admin-media").remove([i.path]); const r = await supabase.from("media_items").delete().eq("id", i.id); if (r.error) toast.error(r.error.message); else void load(); }
  return <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Media Library</h2><p className="text-xs text-muted-foreground">Actual image upload, storage and media records. Images can be selected from Post editor.</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-accent-foreground"><input className="hidden" type="file" accept="image/*" onChange={upload} />{busy ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />} Upload image</label></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">{items.map(i => <div key={i.id} className="overflow-hidden rounded-lg border border-border"><img src={i.url} alt={i.alt_text || i.name} className="aspect-square w-full object-cover" /><div className="p-2"><div className="truncate text-xs">{i.name}</div><button type="button" className="mt-1 text-xs text-destructive" onClick={() => void del(i)}>Delete</button></div></div>)}</div></Card>;
}

function AppearancePanel() {
  const { settings, save } = useSiteSettings(); const [draft, setDraft] = useState<SiteSettings>(settings); useEffect(() => setDraft(settings), [settings]); const setNav = (i: number, patch: any) => setDraft(d => ({ ...d, nav: d.nav.map((n, j) => j === i ? { ...n, ...patch } : n) }));
  return <div className="space-y-5"><Card><h2 className="text-xl font-bold">Theme & Site Layout</h2><p className="mt-1 text-xs text-muted-foreground">Layout-specific controls only: branding, navigation, rate and footer.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field name="Website name" value={draft.siteName} onChange={v => setDraft(d => ({ ...d, siteName: v }))} /><Field name="Logo URL" value={draft.logoUrl} onChange={v => setDraft(d => ({ ...d, logoUrl: v }))} /><Field name="Steel rate" value={String(draft.steelRate)} onChange={v => setDraft(d => ({ ...d, steelRate: Number(v) }))} type="number" /><Field name="Footer text" value={draft.footerText} onChange={v => setDraft(d => ({ ...d, footerText: v }))} /></div><div className="mt-5"><span className={labelCls}>Navigation</span><div className="mt-2 grid gap-2">{draft.nav.map((n, i) => <div key={i} className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input className={inputCls} value={n.label} onChange={e => setNav(i, { label: e.target.value })} /><input className={inputCls} value={n.to} onChange={e => setNav(i, { to: e.target.value })} /><Button variant="danger" onClick={() => setDraft(d => ({ ...d, nav: d.nav.filter((_, j) => j !== i) }))}><Trash2 className="size-4" /></Button></div>)}<Button variant="ghost" onClick={() => setDraft(d => ({ ...d, nav: [...d.nav, { label: "New Link", to: "/" }] }))}><Plus className="size-4" />Add navigation link</Button></div></div><div className="mt-5"><Button onClick={() => { save(draft); toast.success("Website layout saved"); }}><Save className="size-4" />Save layout</Button></div></Card></div>;
}

function SocialPanel() {
  const defaults = { facebook: "", instagram: "", youtube: "", linkedin: "", x: "", whatsapp: "", telegram: "" }; const [v, setV] = useState(defaults); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { const r = await supabase.from("social_settings").select("*").eq("id", true).maybeSingle(); if (r.data) setV({ facebook: r.data.facebook || "", instagram: r.data.instagram || "", youtube: r.data.youtube || "", linkedin: r.data.linkedin || "", x: r.data.x || "", whatsapp: r.data.whatsapp || "", telegram: r.data.telegram || "" }); })(); }, []);
  async function save() { setSaving(true); const r = await supabase.from("social_settings").upsert({ id: true, ...v, updated_at: new Date().toISOString() }); setSaving(false); if (r.error) toast.error(r.error.message); else toast.success("Social media links saved"); }
  return <Card><h2 className="text-xl font-bold">Social Media</h2><p className="mt-1 text-xs text-muted-foreground">These are real saved links. The public header/footer must read the same social_settings row to display them.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(v).map(([k, val]) => <Field key={k} name={k.toUpperCase()} value={val} onChange={x => setV(s => ({ ...s, [k]: x }))} placeholder={`https://${k === "x" ? "x.com" : k + ".com"}/...`} />)}</div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={saving} onClick={() => void save()}><Save className="size-4" />Save social links</Button>{v.facebook && <a className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold" href={v.facebook} target="_blank" rel="noreferrer"><ExternalLink className="size-4" />Preview Facebook</a>}</div></Card>; }

function AdsPanel() {
  const [rows, setRows] = useState<any[]>([]); const load = async () => { const r = await supabase.from("ad_slots").select("*").order("name"); if (!r.error) setRows(r.data || []); }; useEffect(() => { void load(); }, []); const update = (id: string, patch: any) => setRows(x => x.map(r => r.id === id ? { ...r, ...patch } : r));
  async function save(r: any) { const x = await supabase.from("ad_slots").update({ enabled: r.enabled, publisher_id: r.publisher_id, slot_id: r.slot_id, code: r.code, provider: r.provider, updated_at: new Date().toISOString() }).eq("id", r.id); if (x.error) toast.error(x.error.message); else toast.success(`${r.name} saved`); }
  return <Card><h2 className="text-xl font-bold">Ad Manager</h2><p className="mt-1 text-xs text-muted-foreground">Ad-specific controls: provider, publisher, slot IDs, code and enabled state.</p><div className="mt-5 grid gap-3">{rows.map(r => <div key={r.id} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><div><b>{String(r.name || "Ad slot").replaceAll("_", " ")}</b><div className="text-xs text-muted-foreground">{r.placement}</div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!r.enabled} onChange={e => update(r.id, { enabled: e.target.checked })} />Enabled</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field name="Provider" value={r.provider || "adsense"} onChange={v => update(r.id, { provider: v })} /><Field name="Publisher ID" value={r.publisher_id || ""} onChange={v => update(r.id, { publisher_id: v })} /><Field name="Ad Slot ID" value={r.slot_id || ""} onChange={v => update(r.id, { slot_id: v })} /><div><span className={labelCls}>Custom ad code</span><textarea className={`${inputCls} mt-1 min-h-24 font-mono`} value={r.code || ""} onChange={e => update(r.id, { code: e.target.value })} /></div></div><div className="mt-3"><Button onClick={() => void save(r)}><Save className="size-4" />Save slot</Button></div></div>)}</div></Card>;
}

function SeoPanel() {
  const [s, setS] = useState<any>({ id: true, site_title: "", site_description: "", canonical_url: "", robots_txt: "", google_verification: "", bing_verification: "" }); useEffect(() => { (async () => { const r = await supabase.from("seo_settings").select("*").eq("id", true).maybeSingle(); if (r.data) setS(r.data); })(); }, []); async function save() { const r = await supabase.from("seo_settings").upsert({ ...s, id: true, updated_at: new Date().toISOString() }); if (r.error) toast.error(r.error.message); else toast.success("SEO settings saved"); }
  return <Card><h2 className="text-xl font-bold">SEO Settings</h2><p className="mt-1 text-xs text-muted-foreground">SEO-specific metadata and verification controls.</p><div className="mt-5 grid gap-4"><Field name="Site title" value={s.site_title || ""} onChange={v => setS((x: any) => ({ ...x, site_title: v }))} /><div><span className={labelCls}>Site description</span><textarea className={`${inputCls} mt-1 min-h-24`} value={s.site_description || ""} onChange={e => setS((x: any) => ({ ...x, site_description: e.target.value }))} /></div><Field name="Canonical URL" value={s.canonical_url || ""} onChange={v => setS((x: any) => ({ ...x, canonical_url: v }))} /><div className="grid gap-4 sm:grid-cols-2"><Field name="Google verification" value={s.google_verification || ""} onChange={v => setS((x: any) => ({ ...x, google_verification: v }))} /><Field name="Bing verification" value={s.bing_verification || ""} onChange={v => setS((x: any) => ({ ...x, bing_verification: v }))} /></div><div><span className={labelCls}>Robots.txt</span><textarea className={`${inputCls} mt-1 min-h-40 font-mono`} value={s.robots_txt || ""} onChange={e => setS((x: any) => ({ ...x, robots_txt: e.target.value }))} /></div><Button onClick={() => void save()}><Save className="size-4" />Save SEO</Button></div></Card>;
}

function AnalyticsPanel() {
  const [v, setV] = useState({ google: "", gtm: "", searchConsole: "" });
  useEffect(() => { (async () => { const r = await supabase.from("analytics_settings").select("*").eq("id", true).maybeSingle(); if (r.data) setV({ google: r.data.google_analytics_id || "", gtm: r.data.google_tag_manager_id || "", searchConsole: r.data.search_console_verification || "" }); })(); }, []);
  async function save() { const r = await supabase.from("analytics_settings").upsert({ id: true, google_analytics_id: v.google.trim(), google_tag_manager_id: v.gtm.trim(), search_console_verification: v.searchConsole.trim(), updated_at: new Date().toISOString() }); if (r.error) toast.error(r.error.message); else toast.success("Analytics settings saved"); }
  return <Card><h2 className="text-xl font-bold">Analytics</h2><p className="mt-1 text-xs text-muted-foreground">Real database-backed analytics settings from the admin migration.</p><div className="mt-5 grid gap-4"><Field name="Google Analytics / GA4 ID" value={v.google} onChange={x => setV(s => ({ ...s, google: x }))} placeholder="G-XXXXXXXX" /><Field name="Google Tag Manager ID" value={v.gtm} onChange={x => setV(s => ({ ...s, gtm: x }))} placeholder="GTM-XXXXXXX" /><Field name="Search Console verification" value={v.searchConsole} onChange={x => setV(s => ({ ...s, searchConsole: x }))} /><Button onClick={() => void save()}><Save className="size-4" />Save analytics</Button></div></Card>; }

function RedirectsPanel() { const qc = useQueryClient(); const q = useQuery({ queryKey: ["redirects_master"], queryFn: async () => { const r = await supabase.from("redirects").select("*").order("created_at", { ascending: false }); return r.data || []; } }); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [code, setCode] = useState("301"); async function add() { if (!from || !to) return toast.error("From and To paths are required"); const r = await supabase.from("redirects").insert({ from_path: from, to_path: to, status_code: Number(code), enabled: true }); if (r.error) toast.error(r.error.message); else { setFrom(""); setTo(""); toast.success("Redirect added"); void qc.invalidateQueries({ queryKey: ["redirects_master"] }); } } async function del(id: string) { const r = await supabase.from("redirects").delete().eq("id", id); if (r.error) toast.error(r.error.message); else void qc.invalidateQueries({ queryKey: ["redirects_master"] }); } return <div className="space-y-5"><Card><h2 className="text-xl font-bold">Redirect / 404 Manager</h2><div className="mt-5 grid gap-3 sm:grid-cols-3"><Field name="From path" value={from} onChange={setFrom} placeholder="/old-url" /><Field name="To path" value={to} onChange={setTo} placeholder="/new-url" /><label className="grid gap-1"><span className={labelCls}>Status code</span><select className={inputCls} value={code} onChange={e => setCode(e.target.value)}><option>301</option><option>302</option></select></label></div><div className="mt-3"><Button onClick={() => void add()}><Plus className="size-4" />Add redirect</Button></div></Card><Card><div className="grid gap-2">{(q.data || []).map((r: any) => <div key={r.id} className="flex items-center justify-between rounded-lg border border-border p-3"><span className="text-sm">{r.from_path} → {r.to_path} ({r.status_code})</span><Button variant="danger" onClick={() => void del(r.id)}><Trash2 className="size-4" /></Button></div>)}</div></Card></div>; }

function UsersPanel() { const [rows, setRows] = useState<any[]>([]); const [me, setMe] = useState<any>(null); useEffect(() => { (async () => { const u = await supabase.auth.getUser(); setMe(u.data.user); await supabase.rpc("ensure_current_user_admin"); const r = await supabase.from("admin_profiles").select("*").order("created_at"); if (!r.error) setRows(r.data || []); })(); }, []); async function role(id: string, value: string) { const r = await supabase.from("admin_profiles").update({ role: value, updated_at: new Date().toISOString() }).eq("user_id", id); if (r.error) toast.error(r.error.message); else { toast.success("Role updated"); setRows(x => x.map(a => a.user_id === id ? { ...a, role: value } : a)); } } return <Card><h2 className="text-xl font-bold">Users & Roles</h2><p className="mt-1 text-xs text-muted-foreground">Security-specific role control. Authentication remains managed by Supabase Auth.</p><div className="mt-5 grid gap-2">{rows.map(r => <div key={r.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"><div><b>{r.display_name || "User"}</b><div className="text-[11px] text-muted-foreground">{r.user_id}{r.user_id === me?.id ? " · You" : ""}</div></div><select className="rounded border border-input bg-background px-3 py-2 text-sm" value={r.role} onChange={e => void role(r.user_id, e.target.value)}><option>admin</option><option>editor</option><option>viewer</option></select></div>)}{!rows.length && <div className="text-sm text-muted-foreground">No admin profiles found.</div>}</div></Card>; }

function LeadsPanel() { const q = useQuery({ queryKey: ["leads_master"], queryFn: async () => { const r = await supabase.from("leads").select("*").order("created_at", { ascending: false }); return r.data || []; } }); return <Card><h2 className="text-xl font-bold">Leads / Enquiries</h2><p className="mt-1 text-xs text-muted-foreground">Lead data is read-only here to avoid accidentally changing customer records.</p><div className="mt-5 grid gap-2">{(q.data || []).map((l: any) => <div key={l.id} className="rounded-lg border border-border p-3"><b>{l.name || "Lead"}</b><div className="text-xs text-muted-foreground">{l.email}</div><div className="mt-2 text-sm">{l.message}</div></div>)}</div></Card>; }
function ReviewsPanel() { return <Card><h2 className="text-xl font-bold">Reviews</h2><p className="mt-2 text-sm text-muted-foreground">Review moderation is kept separate from content editing. Connect the existing reviews table here when its schema is available.</p></Card>; }
function CommentsPanel() { return <Card><h2 className="text-xl font-bold">Comments</h2><p className="mt-2 text-sm text-muted-foreground">Comment moderation is kept separate from article editing.</p></Card>; }
function SecurityPanel() { return <Card><h2 className="text-xl font-bold">Audit / Security</h2><p className="mt-2 text-sm text-muted-foreground">Security controls remain security-specific. No rich editor or content-quality tools are shown here.</p></Card>; }
function SettingsPanel() { return <Card><h2 className="text-xl font-bold">General Settings</h2><p className="mt-2 text-sm text-muted-foreground">General application settings belong here; site layout, social, SEO and ads have their own panels.</p></Card>; }

function Dashboard() { const posts = useQuery({ queryKey: ["dash_posts_master"], queryFn: async () => { const r = await supabase.from("posts").select("id", { count: "exact", head: true }); return r.count || 0; } }); const pages = useQuery({ queryKey: ["dash_pages_master"], queryFn: async () => { const r = await supabase.from("pages").select("id", { count: "exact", head: true }); return r.count || 0; } }); return <div className="space-y-6"><div><h2 className="text-2xl font-bold">BTTOTEK Master Dashboard</h2><p className="text-sm text-muted-foreground">Control panel where each section exposes only controls belonging to that feature.</p></div><div className="grid gap-3 sm:grid-cols-3"><Card><div className={labelCls}>Posts</div><div className="mt-2 text-3xl font-bold">{posts.data ?? 0}</div></Card><Card><div className={labelCls}>Pages</div><div className="mt-2 text-3xl font-bold">{pages.data ?? 0}</div></Card><Card><div className={labelCls}>Calculators</div><div className="mt-2 text-3xl font-bold">{TOOLS.length}</div></Card></div><Card><h3 className="font-bold">What is different in this master build</h3><div className="mt-3 grid gap-2 text-sm"><div>✓ Rich toolbar appears only on actual content fields.</div><div>✓ Media has real upload/storage + picker.</div><div>✓ Social has social-link controls only.</div><div>✓ Layout has branding/navigation controls only.</div><div>✓ Grammar checker reports detected rules instead of always green.</div><div>✓ Plagiarism indicator compares against existing site content and reports overlap.</div><div>✓ Existing Posts, Pages and FAQs remain editable.</div></div></Card></div>; }

export function AdminConsole() {
  const [tab, setTab] = useState<Tab>("dashboard"); const [open, setOpen] = useState(true); const [ready, setReady] = useState(false); const active = NAV.find(x => x.id === tab)!;
  useEffect(() => { (async () => { const r = await supabase.rpc("ensure_current_user_admin"); setReady(!r.error); if (r.error) toast.error("Admin access setup failed: " + r.error.message); })(); }, []);
  const panel = () => { switch (tab) { case "dashboard": return <Dashboard />; case "posts": return <PostsPanel />; case "pages": return <PagesPanel />; case "faqs": return <FaqsPanel />; case "tools": return <ToolsPanel />; case "media": return <MediaPanel />; case "appearance": return <AppearancePanel />; case "social": return <SocialPanel />; case "adsense": return <AdsPanel />; case "seo": return <SeoPanel />; case "analytics": return <AnalyticsPanel />; case "redirects": return <RedirectsPanel />; case "users": return <UsersPanel />; case "leads": return <LeadsPanel />; case "reviews": return <ReviewsPanel />; case "comments": return <CommentsPanel />; case "security": return <SecurityPanel />; case "settings": return <SettingsPanel />; case "cms": return <AdminCmsSettingsPanel />; default: return <SettingsPanel />; } };
  if (!ready) return <div className="grid min-h-[50vh] place-items-center"><div className="text-sm text-muted-foreground"><Loader2 className="mr-2 inline size-4 animate-spin" />Checking admin access...</div></div>;
  const sections = [...new Set(NAV.map(x => x.section))];
  return <div className="min-h-[calc(100vh-4rem)] bg-background"><div className="flex min-h-[calc(100vh-4rem)]"><aside className={`${open ? "w-72" : "w-14"} shrink-0 border-r border-border bg-card transition-all`}><div className="sticky top-0 flex max-h-[calc(100vh-4rem)] flex-col"><div className="flex items-center justify-between border-b border-border p-3">{open && <div><b>BTTOTEK</b><div className="text-[10px] text-muted-foreground">MASTER ADMIN</div></div>}<button type="button" className="rounded border border-border p-2" onClick={() => setOpen(x => !x)}>{open ? <X className="size-4" /> : <Menu className="size-4" />}</button></div><nav className="overflow-y-auto p-2">{sections.map(section => <div key={section} className="mb-4">{open && <div className="px-2 pb-1 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{section}</div>}{NAV.filter(x => x.section === section).map(item => <button type="button" key={item.id} title={item.label} onClick={() => setTab(item.id)} className={`mb-0.5 flex w-full items-center rounded-lg px-2.5 py-2 text-left text-sm ${tab === item.id ? "bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-secondary hover:text-foreground"}`}>{open ? item.label : item.label.slice(0, 1)}</button>)}</div>)}</nav></div></aside><main className="min-w-0 flex-1 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-5 border-b border-border pb-4"><div className={labelCls}>{active.section}</div><h1 className="mt-1 text-2xl font-bold">{active.label}</h1></div>{panel()}</div></main></div></div>;
}
export default AdminConsole;
