import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      {
        title: "Disclaimer | BTTOTEK Solutions",
      },
      {
        name: "description",
        content:
          "Read the BTTOTEK Solutions disclaimer covering calculator estimates, construction quantities, property and financial calculations, third-party information and general website content.",
      },
      {
        name: "robots",
        content: "index, follow",
      },
    ],
    links: [
      {
        rel: "canonical",
        href: "https://www.bttotek.in/disclaimer",
      },
    ],
  }),

  component: DisclaimerPage,
});

function DisclaimerPage() {
  return (
    <main className="mx-auto w-full max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
      <article className="surface-panel p-6 sm:p-8">
        <header>
          <p className="text-sm font-medium text-primary">
            BTTOTEK Solutions
          </p>

          <h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">
            Disclaimer
          </h1>

          <p className="mt-3 text-sm text-muted-foreground">
            Last updated: August 18, 2026
          </p>
        </header>

        <div className="mt-8 space-y-8 text-sm leading-7 text-muted-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground">
              General Information
            </h2>

            <p className="mt-3">
              The information, calculators, tools, articles and other content
              published on BTTOTEK Solutions are provided for general
              informational and estimation purposes only.
            </p>

            <p className="mt-3">
              While we aim to provide useful and reasonably accurate
              calculations, results may depend on the information entered by
              the user, assumptions, formulas, rates, local practices and
              other external factors.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Calculator Results
            </h2>

            <p className="mt-3">
              Results generated by BTTOTEK calculators are estimates and should
              not be treated as professional engineering, architectural,
              surveying, legal, tax, banking or financial advice.
            </p>

            <p className="mt-3">
              Users should independently verify important calculations before
              using them for construction, procurement, tendering, property
              transactions, investment decisions or other financial or
              professional purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              How to Use Calculator Results
            </h2>

            <p className="mt-3">
              Before relying on a result, check the source of every input,
              confirm the displayed units, review the calculation method and
              compare the output with the applicable drawings, specifications,
              rates, standards or official information.
            </p>

            <p className="mt-3">
              If a calculator does not represent an important project
              condition or assumption, the result should be treated as
              preliminary rather than as a final quantity, design or decision.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Construction and Engineering
            </h2>

            <p className="mt-3">
              Construction quantities and engineering-related estimates may
              vary because of site conditions, structural design, material
              specifications, workmanship, wastage, local standards and
              project-specific requirements.
            </p>

            <p className="mt-3">
              Always consult a qualified engineer, architect, quantity
              surveyor or other appropriate professional for project-specific
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Property and Financial Information
            </h2>

            <p className="mt-3">
              Property valuation, rental yield, EMI, stamp duty, registration
              charges and other financial calculations are provided for
              estimation and educational purposes.
            </p>

            <p className="mt-3">
              Government charges, interest rates, taxes, registration fees,
              circle rates and other financial figures can change. Always
              confirm current rates and applicable rules with the relevant
              government department, lender, bank, registrar or qualified
              professional.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              No Professional Advice
            </h2>

            <p className="mt-3">
              Nothing published on this website should be considered a
              substitute for professional advice. BTTOTEK Solutions does not
              establish an engineer-client, architect-client, lawyer-client,
              tax advisor-client or financial advisor-client relationship
              merely by providing information through this website.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              External Links and Third-Party Information
            </h2>

            <p className="mt-3">
              BTTOTEK Solutions may reference or link to third-party websites,
              services or resources. We do not control third-party websites
              and are not responsible for their content, availability, privacy
              practices or policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Advertising
            </h2>

            <p className="mt-3">
              This website may display advertisements from third-party
              advertising providers. Advertisements may be selected or served
              based on various factors determined by the advertising provider.
            </p>

            <p className="mt-3">
              The presence of an advertisement does not constitute an
              endorsement or guarantee of the advertised product or service by
              BTTOTEK Solutions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Availability and Errors
            </h2>

            <p className="mt-3">
              We work to keep the website and its calculators available and
              useful, but pages, formulas, data sources, third-party services
              and features may change or occasionally contain errors. Users
              should review important outputs rather than relying on a single
              online calculation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Changes to This Disclaimer
            </h2>

            <p className="mt-3">
              We may update this Disclaimer from time to time to reflect
              changes to our website, services or applicable requirements. Any
              updated version will be published on this page.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground">
              Contact
            </h2>

            <p className="mt-3">
              If you have questions about this Disclaimer, please contact
              BTTOTEK Solutions through our{" "}
              <Link
                to="/contact"
                className="font-medium text-primary underline underline-offset-4"
              >
                Contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
